# Generated by Django 3.2.5 on 2021-07-21 09:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0003_producthistory'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='producthistory',
            name='title',
        ),
    ]
