# Generated by Django 3.2.5 on 2021-07-21 10:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0004_remove_producthistory_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='about',
            field=models.TextField(blank=True, help_text='Short Info about Product', null=True),
        ),
        migrations.AddField(
            model_name='producthistory',
            name='about',
            field=models.TextField(blank=True, help_text='Short info about Product', null=True),
        ),
        migrations.AlterField(
            model_name='producthistory',
            name='price',
            field=models.FloatField(help_text='Price of product per item'),
        ),
        migrations.AlterField(
            model_name='producthistory',
            name='quantity',
            field=models.IntegerField(help_text='Quantity of Item'),
        ),
    ]
