# Generated by Django 3.2.5 on 2021-08-02 11:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0010_alter_product_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='producthistory',
            name='category',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
