# Generated by Django 3.2.5 on 2021-08-11 05:29

# Generated by Django 3.2.5 on 2021-08-11 05:27

import itertools
from django.db import migrations
from django.utils.text import slugify


def update_slug_fields(apps, schema_editor):
    Category = apps.get_model("product", "Category")
    Product = apps.get_model("product", "Product")

    for row in Category.objects.all():
        cat_slug = row.slug
        if cat_slug:
            value = row.title
            slug_candidate = slug_original = slugify(value, allow_unicode=True)
            for i in itertools.count(1):
                if not Category.objects.filter(slug=slug_candidate).exists():
                    break
                slug_candidate = "{}-{}".format(slug_original, i)

            row.slug = slug_candidate
        row.save(update_fields=["slug"])

    for row in Product.objects.all():
        prod_slug = row.slug
        if prod_slug:
            value = row.title
            slug_candidate = slug_original = slugify(value, allow_unicode=True)
            for i in itertools.count(1):
                if not Product.objects.filter(slug=slug_candidate).exists():
                    break
                slug_candidate = "{}-{}".format(slug_original, i)
            row.slug = slug_candidate
        row.save(update_fields=["slug"])


class Migration(migrations.Migration):

    dependencies = [
        ("product", "0013_auto_20210811_1114"),
    ]

    operations = [
        migrations.RunPython(
            update_slug_fields, reverse_code=migrations.RunPython.noop
        ),
    ]
