# Generated by Django 3.2.5 on 2021-08-11 05:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("product", "0014_update_slug_fields"),
    ]

    operations = [
        migrations.AlterField(
            model_name="category",
            name="slug",
            field=models.SlugField(unique=True),
        ),
        migrations.AlterField(
            model_name="product",
            name="slug",
            field=models.SlugField(unique=True),
        ),
    ]
