# Generated by Django 3.2.6 on 2021-08-31 10:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0019_create_productTitle'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='title_fk',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='product_title', to='product.producttitle'),
        ),
    ]
