# Generated by Django 3.2.6 on 2021-08-31 10:51

from django.db import migrations


def update_title_fk_field(apps, schema_editor):
    ProductTitle = apps.get_model("product", "ProductTitle")
    Product = apps.get_model("product", "Product")

    title_qs = ProductTitle.objects.all().order_by("id")

    for x in range(1, len(title_qs) + 1):
        obj = Product.objects.get(id=x)
        obj.title_fk = title_qs[x - 1]
        obj.save(update_fields=["title_fk"])


class Migration(migrations.Migration):

    dependencies = [
        ("product", "0020_product_title_fk"),
    ]

    operations = [
        migrations.RunPython(update_title_fk_field),
    ]
