# Generated by Django 3.2.6 on 2021-08-31 11:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0021_update_titleFk_field'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='title',
        ),
    ]
