# Generated by Django 3.2.6 on 2021-08-31 11:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0022_remove_product_title'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='title_fk',
            new_name='title',
        ),
    ]
