# Generated by Django 3.2.6 on 2021-09-03 10:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("product", "0023_rename_title_fk_product_title"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="title_string",
            field=models.CharField(
                blank=True,
                help_text="This field is used by supplier leave title field is empty",
                max_length=250,
                null=True,
            ),
        ),
        migrations.RemoveField(
            model_name="product",
            name="category",
        ),
    ]
