# Generated by Django 3.2.6 on 2021-09-03 10:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("product", "0024_product_title_string"),
    ]

    operations = [
        migrations.AddField(
            model_name="producttitle",
            name="category",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="title_category",
                to="product.category",
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="producttitle",
            name="is_active",
            field=models.BooleanField(default=False),
        ),
    ]
