# Generated by Django 3.2.6 on 2021-12-08 05:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0026_unit'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='unit',
        ),
    ]
