# Generated by Django 3.2.10 on 2022-02-11 05:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0030_product_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='unit',
        ),
        migrations.RemoveField(
            model_name='producthistory',
            name='unit',
        ),
        migrations.AddField(
            model_name='producttitle',
            name='unit',
            field=models.CharField(blank=True, help_text='Standard representation of product e.g: pot, plant, kg, meter', max_length=20, null=True),
        ),
        migrations.DeleteModel(
            name='Unit',
        ),
    ]
