# Generated by Django 3.2.10 on 2022-02-11 06:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0031_auto_20220211_1111'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='title_string',
        ),
    ]
