# Generated by Django 3.2.10 on 2022-02-11 06:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0032_remove_product_title_string'),
    ]

    operations = [
        migrations.AddField(
            model_name='productimage',
            name='featured',
            field=models.BooleanField(default=False, help_text='Featured image of product which will be shown to a buyer'),
        ),
        migrations.AddField(
            model_name='productimage',
            name='is_active',
            field=models.BooleanField(default=False),
        ),
    ]
