# Generated by Django 3.2.10 on 2022-05-03 09:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('geouser', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='geokrishicategory',
            name='image',
        ),
        migrations.RemoveField(
            model_name='geokrishicategory',
            name='level',
        ),
        migrations.RemoveField(
            model_name='geokrishicategory',
            name='lft',
        ),
        migrations.RemoveField(
            model_name='geokrishicategory',
            name='parent',
        ),
        migrations.RemoveField(
            model_name='geokrishicategory',
            name='rght',
        ),
        migrations.RemoveField(
            model_name='geokrishicategory',
            name='slug',
        ),
        migrations.RemoveField(
            model_name='geokrishicategory',
            name='title',
        ),
        migrations.RemoveField(
            model_name='geokrishicategory',
            name='tree_id',
        ),
        migrations.AddField(
            model_name='geokrishicategory',
            name='name',
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='geokrishicategory',
            name='name_ne',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
