# Generated by Django 3.2.10 on 2022-05-04 04:39

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('geouser', '0002_auto_20220503_1522'),
    ]

    operations = [
        migrations.CreateModel(
            name='GeoItems',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('name', models.CharField(max_length=150, null=True)),
                ('marked_price', models.FloatField(null=True, validators=[django.core.validators.MinValueValidator(0.0)])),
                ('description', models.TextField(blank=True, help_text='Short Info about Product', null=True)),
                ('photo', models.ImageField(blank=True, help_text='User Photo, Maximum file size allowed is 2Mb', null=True, upload_to='media/images/geouser_products/')),
                ('sub_category', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='geosubcategory', to='geouser.geokrishisubcategory')),
            ],
            options={
                'ordering': ['-id'],
                'abstract': False,
            },
        ),
    ]
