# Generated by Django 3.2.10 on 2022-05-04 05:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('geouser', '0003_geoitems'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='geokrishiproduct',
            name='category',
        ),
        migrations.RemoveField(
            model_name='geokrishiproduct',
            name='marked_price',
        ),
        migrations.RemoveField(
            model_name='geokrishiproduct',
            name='name',
        ),
        migrations.RemoveField(
            model_name='geokrishiproduct',
            name='photo',
        ),
        migrations.RemoveField(
            model_name='geokrishiproduct',
            name='sub_category',
        ),
        migrations.AddField(
            model_name='geokrishiproduct',
            name='items',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='items', to='geouser.geoitems'),
        ),
    ]
