# Generated by Django 3.2.10 on 2022-05-05 10:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('geouser', '0004_auto_20220504_1100'),
    ]

    operations = [
        migrations.AddField(
            model_name='geoitems',
            name='unit',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
