# Generated by Django 3.2.10 on 2022-05-06 10:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('geouser', '0005_geoitems_unit'),
    ]

    operations = [
        migrations.AddField(
            model_name='geokrishiproduct',
            name='type',
            field=models.CharField(choices=[['market', 'market'], ['self', 'self']], default='MARKET', max_length=50),
        ),
    ]
