# Generated by Django 3.2.10 on 2022-05-08 05:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('geouser', '0006_geokrishiproduct_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='geokrishiproduct',
            name='type',
        ),
        migrations.AddField(
            model_name='geokrishiproduct',
            name='selling_type',
            field=models.CharField(choices=[['market', 'market'], ['self', 'self']], default='market', max_length=50),
        ),
    ]
