# Generated by Django 3.2.10 on 2022-05-10 06:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('geouser', '0007_auto_20220508_1109'),
    ]

    operations = [
        migrations.RenameField(
            model_name='geokrishiproduct',
            old_name='avaliable_date',
            new_name='availableDate',
        ),
        migrations.RenameField(
            model_name='geokrishiproduct',
            old_name='expiry_date',
            new_name='expiryDate',
        ),
    ]
