# Generated by Django 3.2.10 on 2022-05-19 10:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('geouser', '0008_auto_20220510_1214'),
    ]

    operations = [
        migrations.AddField(
            model_name='geokrishiproduct',
            name='unit',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
