# Generated by Django 3.2.10 on 2022-05-25 09:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('geouser', '0009_geokrishiproduct_unit'),
    ]

    operations = [
        migrations.RenameField(
            model_name='geokrishiproduct',
            old_name='availableDate',
            new_name='available_date',
        ),
        migrations.RenameField(
            model_name='geokrishiproduct',
            old_name='expiryDate',
            new_name='expiry_date',
        ),
    ]
