# Generated by Django 3.2.10 on 2022-06-14 04:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('meta', '0001_initial'),
        ('geouser', '0010_auto_20220525_1523'),
    ]

    operations = [
        migrations.AddField(
            model_name='geokrishiusers',
            name='districid',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='meta.district'),
        ),
        migrations.AddField(
            model_name='geokrishiusers',
            name='muniid',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='meta.palika'),
        ),
        migrations.AlterField(
            model_name='geokrishiusers',
            name='district',
            field=models.CharField(blank=True, db_index=True, max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='geokrishiusers',
            name='municipality',
            field=models.CharField(blank=True, db_index=True, max_length=150, null=True),
        ),
    ]
