# Generated by Django 3.2.10 on 2022-06-14 05:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('geouser', '0011_auto_20220614_1000'),
    ]

    operations = [
        migrations.AlterField(
            model_name='geokrishiusers',
            name='photo',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
