# Generated by Django 3.2.10 on 2022-06-14 06:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('geouser', '0013_auto_20220614_1054'),
    ]

    operations = [
        migrations.AddField(
            model_name='geokrishiproduct',
            name='available_date_eng',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='geokrishiproduct',
            name='available_date_nep',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='geokrishiproduct',
            name='expiry_date_eng',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='geokrishiproduct',
            name='expiry_date_nep',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
    ]
