# Generated by Django 3.2.13 on 2022-06-29 11:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('geouser', '0014_auto_20220614_1201'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='geokrishiproduct',
            name='unit',
        ),
    ]
