# Generated by Django 3.2.13 on 2022-07-05 06:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('geouser', '0015_remove_geokrishiproduct_unit'),
    ]

    operations = [
        migrations.AddField(
            model_name='geoitems',
            name='name_nep',
            field=models.CharField(max_length=150, null=True),
        ),
    ]
