# Generated by Django 3.2.13 on 2022-07-05 08:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('geouser', '0015_geokrishiusers_project'),
        ('geouser', '0016_geoitems_name_nep'),
    ]

    operations = [
    ]
