# Generated by Django 3.2.13 on 2022-07-08 06:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('geouser', '0018_rename_name_ne_geokrishisubcategory_name_nep'),
    ]

    operations = [
        migrations.AddField(
            model_name='geokrishiproduct',
            name='status',
            field=models.CharField(blank=True, choices=[['available', 'available'], ['expired', 'expired'], ['sold', 'sold']], max_length=50, null=True),
        ),
    ]
