# Generated by Django 3.2.13 on 2022-07-08 10:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('geouser', '0019_geokrishiproduct_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='geokrishiproduct',
            name='status',
            field=models.CharField(blank=True, choices=[['available', 'available'], ['sold', 'sold']], max_length=50, null=True),
        ),
    ]
