# Generated by Django 3.2.13 on 2022-07-15 05:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('geouser', '0021_alter_geokrishiproduct_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='geokrishiproduct',
            name='selling_type',
        ),
        migrations.AlterField(
            model_name='geokrishiproduct',
            name='status',
            field=models.CharField(choices=[['available', 'available'], ['sold', 'sold'], ['expired', 'expired']], default='available', max_length=50),
        ),
    ]
