# Generated by Django 3.2.14 on 2022-08-04 04:24

from django.db import migrations, models


def update_sold_date(apps, schema_editor):
    GeokrishiProduct = apps.get_model("geouser", "GeokrishiProduct")
    for product in GeokrishiProduct.objects.all():
        if product.status == "sold":
            product.sold_date = product.updated_at
            product.save(update_fields=["sold_date"])


class Migration(migrations.Migration):

    dependencies = [
        ("geouser", "0022_auto_20220715_1117"),
    ]

    operations = [
        migrations.AddField(
            model_name="geokrishiproduct",
            name="sold_date",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="geokrishiproduct",
            name="status",
            field=models.CharField(
                choices=[
                    ["available", "available"],
                    ["sold", "sold"],
                    ["expired", "expired"],
                    ["canceled", "canceled"],
                ],
                default="available",
                max_length=50,
            ),
        ),
        migrations.RunPython(update_sold_date, reverse_code=migrations.RunPython.noop),
    ]
