# Generated by Django 3.2.14 on 2022-08-05 06:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('geouser', '0024_geokrishiproduct_order'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='geokrishiproduct',
            name='order',
        ),
    ]
