# Generated by Django 3.2.10 on 2021-12-16 05:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('buyer_app', '0003_auto_20211210_1223'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='remarks',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('new', 'New'), ('cancelled', 'Cancelled'), ('processing', 'Processing'), ('confirmed', 'Confirmed'), ('dispatched', 'Dispatched')], default='new', max_length=50),
        ),
    ]
