# Generated by Django 3.2.10 on 2022-02-14 10:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0033_auto_20220211_1232'),
        ('buyer_app', '0005_auto_20211221_1014'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='product_title',
            field=models.ForeignKey(blank=True, help_text='Order product with selected product title', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='order_of', to='product.producttitle'),
        ),
    ]
