# Generated by Django 3.2.10 on 2022-02-14 10:42

from django.db import migrations


def copy_product_to_product_title(apps, schema_editor):
    Order = apps.get_model("buyer_app", "Order")
    for row in Order.objects.all():
        row.product_title = row.product.title
        row.save(update_fields=["product_title"])


class Migration(migrations.Migration):

    dependencies = [
        ("buyer_app", "0006_order_product_title"),
    ]

    operations = [
        # omit reverse_code=... if you don't want the migration to be reversible.
        migrations.RunPython(
            copy_product_to_product_title, reverse_code=migrations.RunPython.noop
        ),
    ]
