# Generated by Django 3.2.5 on 2021-07-24 02:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='profile',
            options={'ordering': ['-id']},
        ),
        migrations.AlterModelOptions(
            name='vendor',
            options={'ordering': ['-id']},
        ),
    ]
