# Generated by Django 3.2.5 on 2021-07-28 06:08

from django.db import migrations, models
import utils.validations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_auto_20210724_0836'),
    ]

    operations = [
        migrations.AddField(
            model_name='vendor',
            name='location',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='vendor',
            name='phone_number',
            field=models.CharField(blank=True, max_length=10, null=True, validators=[utils.validations.phone_number_validation]),
        ),
    ]
