# Generated by Django 3.2.6 on 2021-08-24 08:19

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import utils.validations


class Migration(migrations.Migration):

    dependencies = [
        ('meta', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('user', '0003_auto_20210728_1153'),
    ]

    operations = [
        migrations.CreateModel(
            name='AdminEmail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=254)),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
        migrations.AlterField(
            model_name='profile',
            name='user_type',
            field=models.CharField(choices=[('buyer', 'Buyer'), ('vendor', 'Vendor'), ('admin', 'Admin')], max_length=50),
        ),
        migrations.CreateModel(
            name='Buyer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('company_name', models.CharField(help_text='Company name', max_length=255)),
                ('contact_person', models.CharField(help_text='Name of contact person', max_length=255)),
                ('contact_number', models.CharField(help_text='Contact number of company', max_length=10, validators=[utils.validations.phone_number_validation])),
                ('mobile_number', models.CharField(help_text='Mobile number of company/buyer', max_length=10, validators=[utils.validations.mobile_number_validation])),
                ('ward', models.IntegerField(blank=True, null=True)),
                ('tole', models.CharField(default='', max_length=255)),
                ('auth_user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='buyer', to=settings.AUTH_USER_MODEL)),
                ('district', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='buyers', to='meta.district')),
                ('palika', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='buyers', to='meta.palika')),
                ('province', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='buyers', to='meta.province')),
            ],
            options={
                'ordering': ['-id'],
                'abstract': False,
            },
        ),
    ]
