# Generated by Django 3.2.6 on 2021-09-27 06:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('meta', '0001_initial'),
        ('user', '0004_auto_20210824_1404'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vendor',
            name='location',
        ),
        migrations.AddField(
            model_name='vendor',
            name='district',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='vendors', to='meta.district'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='vendor',
            name='palika',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='vendors', to='meta.palika'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='vendor',
            name='province',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='vendors', to='meta.province'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='vendor',
            name='tole',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AddField(
            model_name='vendor',
            name='ward',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
