# Generated by Django 3.2.6 on 2021-10-06 06:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('meta', '0001_initial'),
        ('user', '0005_auto_20210927_1230'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='buyer',
            name='district',
        ),
        migrations.RemoveField(
            model_name='buyer',
            name='palika',
        ),
        migrations.RemoveField(
            model_name='buyer',
            name='province',
        ),
        migrations.RemoveField(
            model_name='buyer',
            name='tole',
        ),
        migrations.RemoveField(
            model_name='buyer',
            name='ward',
        ),
        migrations.RemoveField(
            model_name='vendor',
            name='district',
        ),
        migrations.RemoveField(
            model_name='vendor',
            name='palika',
        ),
        migrations.RemoveField(
            model_name='vendor',
            name='province',
        ),
        migrations.RemoveField(
            model_name='vendor',
            name='tole',
        ),
        migrations.RemoveField(
            model_name='vendor',
            name='ward',
        ),
        migrations.AddField(
            model_name='profile',
            name='district',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='meta.district'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='profile',
            name='palika',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='meta.palika'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='profile',
            name='province',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='meta.province'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='profile',
            name='tole',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AddField(
            model_name='profile',
            name='ward',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
