# Generated by Django 3.2.10 on 2021-12-09 06:48

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import utils.validations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('user', '0006_auto_20211006_1209'),
    ]

    operations = [
        migrations.CreateModel(
            name='Trader',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('company_name', models.CharField(help_text='Company name', max_length=250)),
                ('contact_person', models.CharField(help_text='Name of contact person', max_length=255)),
                ('contact_number', models.CharField(help_text='Contact number of company', max_length=10, validators=[utils.validations.phone_number_validation])),
                ('mobile_number', models.CharField(help_text='Mobile number of buyer/vendor', max_length=10, validators=[utils.validations.mobile_number_validation])),
                ('auth_user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='trader', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-id'],
                'abstract': False,
            },
        ),
    ]
