# Generated by Django 3.2.10 on 2021-12-09 11:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0007_trader'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='user_type',
        ),
    ]
