# Generated by Django 3.2.10 on 2021-12-10 06:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0008_remove_profile_user_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vendor',
            name='auth_user',
        ),
        migrations.DeleteModel(
            name='Buyer',
        ),
        migrations.DeleteModel(
            name='Vendor',
        ),
    ]
