# Generated by Django 3.2.10 on 2022-02-16 05:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0010_trader_category_associated_with'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='latitude',
            field=models.FloatField(blank=True, help_text="Latitude of Trader's location", null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='longitude',
            field=models.FloatField(blank=True, help_text="Longitude of Trader's location", null=True),
        ),
    ]
